---
language: go
go:
  - "1.x"
  - "1.8"
  - "1.9"
  - "1.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsnmp-dev snmp-mibs-downloader
before_script:
  - go get -v github.com/stretchr/testify
